# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Interview < Formula
  desc "A tool to generate interview question!"
  homepage "https://github.com/borischen0203/interview"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.5/interview_0.0.5_macOS-64bit.tar.gz"
      sha256 "2fa55f039cc075c22af091344cf6febc0a0d65a94d8f682a8cecdd0200ae07d8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.5/interview_0.0.5_macOS-ARM64.tar.gz"
      sha256 "5a9359c18109f3d71405f869aa4be5d25908609a288e90c9ea123a4b39636187"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.5/interview_0.0.5_Linux-64bit.tar.gz"
      sha256 "1e16d4654ff085c7229dc4fc14d7cfe32e74b24c5672c4d5e0cdb18fee288b47"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.5/interview_0.0.5_Linux-ARM64.tar.gz"
      sha256 "94eebedf44abf8fa2aee9726c78affd1a0813d78a56d85a147350a8c68883394"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "interview"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
