# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Interview < Formula
  desc "A tool to generate interview question!"
  homepage "https://github.com/borischen0203/interview"
  version "0.0.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.6/interview_0.0.6_macOS-64bit.tar.gz"
      sha256 "5e530606aac954166aabbf2942bf356773f5d387467ad4e080fb637101cb64f4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.6/interview_0.0.6_macOS-ARM64.tar.gz"
      sha256 "cc6d7d0ada725ebc273eda2a3e0f914f2c42b7df86e874d01d3dc0b3ad8391f6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.6/interview_0.0.6_Linux-64bit.tar.gz"
      sha256 "b0fc62f2cf37f6b5e861cb998ddcc4a3425728808bc78f536003442cf904e44b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.6/interview_0.0.6_Linux-ARM64.tar.gz"
      sha256 "fe449f970d87582bf8d17a24a762160d5edfa00979a89444b35b4c1832798a51"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "interview"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
