# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Interview < Formula
  desc "A tool to generate interview question!"
  homepage "https://github.com/borischen0203/interview"
  version "0.0.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.3/interview_0.0.3_macOS-64bit.tar.gz"
      sha256 "912780b7b13372b3fdbe28a2b4d632cf7e6e1fe8219bc65a9ba8b6944de0f908"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.3/interview_0.0.3_macOS-ARM64.tar.gz"
      sha256 "0d2c520a43f953e5221c20004a360a531abf84507fce5f933aedcb0448034be0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.3/interview_0.0.3_Linux-64bit.tar.gz"
      sha256 "3a3a0beaf7d12045e2f7ca660800ab97ecb1b8f9c948870143224fd3a5c83a0f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/interview/releases/download/v0.0.3/interview_0.0.3_Linux-ARM64.tar.gz"
      sha256 "b56e27a73445d9b9540a3d6bce4c13a251d31c8bc2d6093f24016312329b262f"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "interview"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
